# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b88bb3a27b8dd0be579b41ada8e1fbfc9e91bd31f89b69c9562e12e0ce16aaf6c7f4681a0d83679c191b749c7fdd2a0133f5037d591894910df3d23e02014080

test:
  secret_key_base: 2d84de7c663755aea8d21b61b4afbd6b9b61c1a572c53d30849de7663b6e1e845a8f5813c2f14f98e84adbafea997c216306e1e482364c882ce64948feeb9280

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
